/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const $t: typeof import('~/i18n')['$t']
  const A: typeof import('~/i18n')['A']
  const cache: typeof import('@solidjs/router')['cache']
  const useParams: typeof import('@solidjs/router')['useParams']
}
